2017-05-09 15:28:16,428 [5] ERROR Customer.WebApi.Filters.CustomerServiceExceptionAttribute - Exception of type 'CustomerService.Exceptions.EntityNotFoundException' was thrown.
CustomerService.Exceptions.EntityNotFoundException: Exception of type 'CustomerService.Exceptions.EntityNotFoundException' was thrown.
   at CustomerService.Repository.CustomerRepository.GetById(Int32 id) in C:\Sources\Repos\CustomerModule\CustomerService\Repository\CustomerRepository.cs:line 29
   at CustomerService.CustomerService.GetById(Int32 id) in C:\Sources\Repos\CustomerModule\CustomerService\CustomerService.cs:line 52
   at Customer.WebApi.Controllers.CustomerController.Get(Int32 id) in C:\Sources\Repos\CustomerModule\Customer.WebApi\Controllers\CustomerController.cs:line 25
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
